/* autostart.c generated by valac 0.22.1, the Vala compiler
 * generated from autostart.vala, do not modify */

/* 
 *      Copyright 2011 Julien Lavergne <gilir@ubuntu.com>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG (lxsession_lxsession_autostart_config_get_type ())
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfig))
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfigClass))
#define LXSESSION_IS_LXSESSION_AUTOSTART_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG))
#define LXSESSION_IS_LXSESSION_AUTOSTART_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG))
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfigClass))

typedef struct _LxsessionLxsessionAutostartConfig LxsessionLxsessionAutostartConfig;
typedef struct _LxsessionLxsessionAutostartConfigClass LxsessionLxsessionAutostartConfigClass;
typedef struct _LxsessionLxsessionAutostartConfigPrivate LxsessionLxsessionAutostartConfigPrivate;

#define LXSESSION_TYPE_APP_TYPE (lxsession_app_type_get_type ())
typedef struct _LxsessionAppType LxsessionAppType;
#define _g_array_free0(var) ((var == NULL) ? NULL : (var = (g_array_free (var, TRUE), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define LXSESSION_TYPE_APP_OBJECT (lxsession_app_object_get_type ())
#define LXSESSION_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_APP_OBJECT, LxsessionAppObject))
#define LXSESSION_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_APP_OBJECT, LxsessionAppObjectClass))
#define LXSESSION_IS_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_APP_OBJECT))
#define LXSESSION_IS_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_APP_OBJECT))
#define LXSESSION_APP_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_APP_OBJECT, LxsessionAppObjectClass))

typedef struct _LxsessionAppObject LxsessionAppObject;
typedef struct _LxsessionAppObjectClass LxsessionAppObjectClass;

#define LXSESSION_TYPE_GENERIC_APP_OBJECT (lxsession_generic_app_object_get_type ())
#define LXSESSION_GENERIC_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_GENERIC_APP_OBJECT, LxsessionGenericAppObject))
#define LXSESSION_GENERIC_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_GENERIC_APP_OBJECT, LxsessionGenericAppObjectClass))
#define LXSESSION_IS_GENERIC_APP_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_GENERIC_APP_OBJECT))
#define LXSESSION_IS_GENERIC_APP_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_GENERIC_APP_OBJECT))
#define LXSESSION_GENERIC_APP_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_GENERIC_APP_OBJECT, LxsessionGenericAppObjectClass))

typedef struct _LxsessionGenericAppObject LxsessionGenericAppObject;
typedef struct _LxsessionGenericAppObjectClass LxsessionGenericAppObjectClass;

struct _LxsessionLxsessionAutostartConfig {
	GObject parent_instance;
	LxsessionLxsessionAutostartConfigPrivate * priv;
};

struct _LxsessionLxsessionAutostartConfigClass {
	GObjectClass parent_class;
};

struct _LxsessionAppType {
	gchar* name;
	gchar** command;
	gint command_length1;
	gboolean guard;
	gchar* application_type;
};

struct _LxsessionLxsessionAutostartConfigPrivate {
	GArray* stock_list;
};


static gpointer lxsession_lxsession_autostart_config_parent_class = NULL;

GType lxsession_lxsession_autostart_config_get_type (void) G_GNUC_CONST;
GType lxsession_app_type_get_type (void) G_GNUC_CONST;
LxsessionAppType* lxsession_app_type_dup (const LxsessionAppType* self);
void lxsession_app_type_free (LxsessionAppType* self);
void lxsession_app_type_copy (const LxsessionAppType* self, LxsessionAppType* dest);
void lxsession_app_type_destroy (LxsessionAppType* self);
#define LXSESSION_LXSESSION_AUTOSTART_CONFIG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfigPrivate))
enum  {
	LXSESSION_LXSESSION_AUTOSTART_CONFIG_DUMMY_PROPERTY
};
LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_new (void);
LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_construct (GType object_type);
GArray* lxsession_lxsession_autostart_config_load_autostart_file (LxsessionLxsessionAutostartConfig* self);
gchar* lxsession_get_config_path (const gchar* conf_file);
static gchar** _vala_array_dup4 (gchar** self, int length);
static gchar** _vala_array_dup5 (gchar** self, int length);
void lxsession_lxsession_autostart_config_start_applications (LxsessionLxsessionAutostartConfig* self);
GType lxsession_app_object_get_type (void) G_GNUC_CONST;
GType lxsession_generic_app_object_get_type (void) G_GNUC_CONST;
LxsessionGenericAppObject* lxsession_generic_app_object_new (LxsessionAppType* app_type);
LxsessionGenericAppObject* lxsession_generic_app_object_construct (GType object_type, LxsessionAppType* app_type);
void lxsession_app_object_launch (LxsessionAppObject* self);
void lxsession_lxsession_autostart_config_check_dupplicate (LxsessionLxsessionAutostartConfig* self);
static void lxsession_lxsession_autostart_config_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_construct (GType object_type) {
	LxsessionLxsessionAutostartConfig * self = NULL;
	GArray* _tmp0_ = NULL;
	self = (LxsessionLxsessionAutostartConfig*) g_object_new (object_type, NULL);
	_tmp0_ = lxsession_lxsession_autostart_config_load_autostart_file (self);
	_g_array_free0 (self->priv->stock_list);
	self->priv->stock_list = _tmp0_;
	return self;
}


LxsessionLxsessionAutostartConfig* lxsession_lxsession_autostart_config_new (void) {
	return lxsession_lxsession_autostart_config_construct (LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG);
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	glong _tmp2_ = 0L;
	glong _tmp5_ = 0L;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_ = 0L;
	gboolean _tmp12_ = FALSE;
	gboolean _tmp13_ = FALSE;
	glong _tmp14_ = 0L;
	gboolean _tmp17_ = FALSE;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	glong _tmp22_ = 0L;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_ = 0L;
		glong _tmp7_ = 0L;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	_tmp12_ = _tmp8_;
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp14_ = end;
	if (_tmp14_ >= ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = end;
		_tmp16_ = string_length;
		_tmp13_ = _tmp15_ <= _tmp16_;
	} else {
		_tmp13_ = FALSE;
	}
	_tmp17_ = _tmp13_;
	g_return_val_if_fail (_tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	g_return_val_if_fail (_tmp18_ <= _tmp19_, NULL);
	_tmp20_ = start;
	_tmp21_ = end;
	_tmp22_ = start;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) (_tmp21_ - _tmp22_));
	result = _tmp23_;
	return result;
}


static gchar** _vala_array_dup4 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_ = NULL;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static gpointer _lxsession_app_type_dup0 (gpointer self) {
	return self ? lxsession_app_type_dup (self) : NULL;
}


static gchar** _vala_array_dup5 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_ = NULL;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


GArray* lxsession_lxsession_autostart_config_load_autostart_file (LxsessionLxsessionAutostartConfig* self) {
	GArray* result = NULL;
	GFile* file = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	GArray* app_list = NULL;
	GArray* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GFile* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = lxsession_get_config_path ("autostart");
	_tmp1_ = _tmp0_;
	_tmp2_ = g_file_new_for_path (_tmp1_);
	_tmp3_ = _tmp2_;
	_g_free0 (_tmp1_);
	file = _tmp3_;
	_tmp4_ = g_array_new (TRUE, TRUE, sizeof (LxsessionAppType*));
	app_list = _tmp4_;
	_tmp5_ = file;
	_tmp6_ = g_file_get_path (_tmp5_);
	_tmp7_ = _tmp6_;
	g_message ("autostart.vala:42: Autostart path : %s", _tmp7_);
	_g_free0 (_tmp7_);
	_tmp8_ = file;
	_tmp9_ = g_file_query_exists (_tmp8_, NULL);
	if (_tmp9_) {
		{
			GFileInputStream* _tmp10_ = NULL;
			GFile* _tmp11_ = NULL;
			GFileInputStream* _tmp12_ = NULL;
			GDataInputStream* dis = NULL;
			GFileInputStream* _tmp13_ = NULL;
			GDataInputStream* _tmp14_ = NULL;
			GDataInputStream* _tmp15_ = NULL;
			gchar* line = NULL;
			_tmp11_ = file;
			_tmp12_ = g_file_read (_tmp11_, NULL, &_inner_error_);
			_tmp10_ = _tmp12_;
			if (_inner_error_ != NULL) {
				goto __catch6_g_error;
			}
			_tmp13_ = _tmp10_;
			_tmp14_ = g_data_input_stream_new ((GInputStream*) _tmp13_);
			_tmp15_ = _tmp14_;
			_g_object_unref0 (_tmp13_);
			dis = _tmp15_;
			while (TRUE) {
				gchar* _tmp16_ = NULL;
				GDataInputStream* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
				const gchar* _tmp19_ = NULL;
				gchar* first = NULL;
				const gchar* _tmp20_ = NULL;
				gchar* _tmp21_ = NULL;
				const gchar* _tmp22_ = NULL;
				const gchar* _tmp23_ = NULL;
				GQuark _tmp25_ = 0U;
				static GQuark _tmp24_label0 = 0;
				static GQuark _tmp24_label1 = 0;
				_tmp17_ = dis;
				_tmp18_ = g_data_input_stream_read_line (_tmp17_, NULL, NULL, &_inner_error_);
				_tmp16_ = _tmp18_;
				if (_inner_error_ != NULL) {
					_g_free0 (line);
					_g_object_unref0 (dis);
					goto __catch6_g_error;
				}
				_g_free0 (line);
				line = _tmp16_;
				_tmp19_ = line;
				if (!(_tmp19_ != NULL)) {
					break;
				}
				_tmp20_ = line;
				_tmp21_ = string_slice (_tmp20_, (glong) 0, (glong) 1);
				first = _tmp21_;
				_tmp22_ = first;
				_tmp23_ = _tmp22_;
				_tmp25_ = (NULL == _tmp23_) ? 0 : g_quark_from_string (_tmp23_);
				if (_tmp25_ == ((0 != _tmp24_label0) ? _tmp24_label0 : (_tmp24_label0 = g_quark_from_static_string ("@")))) {
					switch (0) {
						default:
						{
							GString* builder = NULL;
							GString* _tmp26_ = NULL;
							GString* _tmp27_ = NULL;
							const gchar* _tmp28_ = NULL;
							GString* _tmp29_ = NULL;
							gchar** command = NULL;
							GString* _tmp30_ = NULL;
							const gchar* _tmp31_ = NULL;
							gchar** _tmp32_ = NULL;
							gchar** _tmp33_ = NULL;
							gint command_length1 = 0;
							gint _command_size_ = 0;
							LxsessionAppType app = {0};
							gchar** _tmp34_ = NULL;
							gint _tmp34__length1 = 0;
							const gchar* _tmp35_ = NULL;
							gchar* _tmp36_ = NULL;
							gchar** _tmp37_ = NULL;
							gint _tmp37__length1 = 0;
							gchar** _tmp38_ = NULL;
							gint _tmp38__length1 = 0;
							gchar* _tmp39_ = NULL;
							LxsessionAppType _tmp40_ = {0};
							GArray* _tmp41_ = NULL;
							LxsessionAppType _tmp42_ = {0};
							LxsessionAppType _tmp43_ = {0};
							LxsessionAppType* _tmp44_ = NULL;
							_tmp26_ = g_string_new ("");
							builder = _tmp26_;
							_tmp27_ = builder;
							_tmp28_ = line;
							g_string_append (_tmp27_, _tmp28_);
							_tmp29_ = builder;
							g_string_erase (_tmp29_, (gssize) 0, (gssize) 1);
							_tmp30_ = builder;
							_tmp31_ = _tmp30_->str;
							_tmp33_ = _tmp32_ = g_strsplit_set (_tmp31_, " ", 0);
							command = _tmp33_;
							command_length1 = _vala_array_length (_tmp32_);
							_command_size_ = command_length1;
							_tmp34_ = command;
							_tmp34__length1 = command_length1;
							_tmp35_ = _tmp34_[0];
							_tmp36_ = g_strdup (_tmp35_);
							_tmp37_ = command;
							_tmp37__length1 = command_length1;
							_tmp38_ = (_tmp37_ != NULL) ? _vala_array_dup4 (_tmp37_, _tmp37__length1) : ((gpointer) _tmp37_);
							_tmp38__length1 = _tmp37__length1;
							_tmp39_ = g_strdup ("");
							_g_free0 (_tmp40_.name);
							_tmp40_.name = _tmp36_;
							_tmp40_.command = (_vala_array_free (_tmp40_.command, _tmp40_.command_length1, (GDestroyNotify) g_free), NULL);
							_tmp40_.command = _tmp38_;
							_tmp40_.command_length1 = _tmp38__length1;
							_tmp40_.guard = TRUE;
							_g_free0 (_tmp40_.application_type);
							_tmp40_.application_type = _tmp39_;
							app = _tmp40_;
							_tmp41_ = app_list;
							_tmp42_ = app;
							_tmp43_ = _tmp42_;
							_tmp44_ = _lxsession_app_type_dup0 (&_tmp43_);
							g_array_append_val (_tmp41_, _tmp44_);
							lxsession_app_type_destroy (&app);
							command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
							_g_string_free0 (builder);
							break;
						}
					}
				} else if (_tmp25_ == ((0 != _tmp24_label1) ? _tmp24_label1 : (_tmp24_label1 = g_quark_from_static_string ("#")))) {
					switch (0) {
						default:
						{
							break;
						}
					}
				} else {
					switch (0) {
						default:
						{
							gchar** command = NULL;
							const gchar* _tmp45_ = NULL;
							gchar** _tmp46_ = NULL;
							gchar** _tmp47_ = NULL;
							gint command_length1 = 0;
							gint _command_size_ = 0;
							LxsessionAppType app = {0};
							gchar** _tmp48_ = NULL;
							gint _tmp48__length1 = 0;
							const gchar* _tmp49_ = NULL;
							gchar* _tmp50_ = NULL;
							gchar** _tmp51_ = NULL;
							gint _tmp51__length1 = 0;
							gchar** _tmp52_ = NULL;
							gint _tmp52__length1 = 0;
							gchar* _tmp53_ = NULL;
							LxsessionAppType _tmp54_ = {0};
							GArray* _tmp55_ = NULL;
							LxsessionAppType _tmp56_ = {0};
							LxsessionAppType _tmp57_ = {0};
							LxsessionAppType* _tmp58_ = NULL;
							_tmp45_ = line;
							_tmp47_ = _tmp46_ = g_strsplit_set (_tmp45_, " ", 0);
							command = _tmp47_;
							command_length1 = _vala_array_length (_tmp46_);
							_command_size_ = command_length1;
							_tmp48_ = command;
							_tmp48__length1 = command_length1;
							_tmp49_ = _tmp48_[0];
							_tmp50_ = g_strdup (_tmp49_);
							_tmp51_ = command;
							_tmp51__length1 = command_length1;
							_tmp52_ = (_tmp51_ != NULL) ? _vala_array_dup5 (_tmp51_, _tmp51__length1) : ((gpointer) _tmp51_);
							_tmp52__length1 = _tmp51__length1;
							_tmp53_ = g_strdup ("");
							_g_free0 (_tmp54_.name);
							_tmp54_.name = _tmp50_;
							_tmp54_.command = (_vala_array_free (_tmp54_.command, _tmp54_.command_length1, (GDestroyNotify) g_free), NULL);
							_tmp54_.command = _tmp52_;
							_tmp54_.command_length1 = _tmp52__length1;
							_tmp54_.guard = FALSE;
							_g_free0 (_tmp54_.application_type);
							_tmp54_.application_type = _tmp53_;
							app = _tmp54_;
							_tmp55_ = app_list;
							_tmp56_ = app;
							_tmp57_ = _tmp56_;
							_tmp58_ = _lxsession_app_type_dup0 (&_tmp57_);
							g_array_append_val (_tmp55_, _tmp58_);
							lxsession_app_type_destroy (&app);
							command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
							break;
						}
					}
				}
				_g_free0 (first);
			}
			_g_free0 (line);
			_g_object_unref0 (dis);
		}
		goto __finally6;
		__catch6_g_error:
		{
			GError* e = NULL;
			const gchar* _tmp59_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp59_ = e->message;
			g_error ("autostart.vala:75: %s", _tmp59_);
			_g_error_free0 (e);
		}
		__finally6:
		if (_inner_error_ != NULL) {
			_g_array_free0 (app_list);
			_g_object_unref0 (file);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	result = app_list;
	_g_object_unref0 (file);
	return result;
}


void lxsession_lxsession_autostart_config_start_applications (LxsessionLxsessionAutostartConfig* self) {
	g_return_if_fail (self != NULL);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_ = FALSE;
				gint _tmp3_ = 0;
				GArray* _tmp4_ = NULL;
				guint _tmp5_ = 0U;
				LxsessionAppType s = {0};
				GArray* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				LxsessionAppType* _tmp8_ = NULL;
				LxsessionGenericAppObject* launch_app = NULL;
				LxsessionAppType _tmp9_ = {0};
				LxsessionGenericAppObject* _tmp10_ = NULL;
				LxsessionGenericAppObject* _tmp11_ = NULL;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_ = 0;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = self->priv->stock_list;
				_tmp5_ = _tmp4_->len;
				if (!(((guint) _tmp3_) < _tmp5_)) {
					break;
				}
				_tmp6_ = self->priv->stock_list;
				_tmp7_ = i;
				_tmp8_ = g_array_index (_tmp6_, LxsessionAppType*, (guint) _tmp7_);
				s = *_tmp8_;
				_tmp9_ = s;
				_tmp10_ = lxsession_generic_app_object_new (&_tmp9_);
				launch_app = _tmp10_;
				_tmp11_ = launch_app;
				lxsession_app_object_launch ((LxsessionAppObject*) _tmp11_);
				_g_object_unref0 (launch_app);
			}
		}
	}
}


void lxsession_lxsession_autostart_config_check_dupplicate (LxsessionLxsessionAutostartConfig* self) {
	g_return_if_fail (self != NULL);
}


static void lxsession_lxsession_autostart_config_class_init (LxsessionLxsessionAutostartConfigClass * klass) {
	lxsession_lxsession_autostart_config_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LxsessionLxsessionAutostartConfigPrivate));
	G_OBJECT_CLASS (klass)->finalize = lxsession_lxsession_autostart_config_finalize;
}


static void lxsession_lxsession_autostart_config_instance_init (LxsessionLxsessionAutostartConfig * self) {
	self->priv = LXSESSION_LXSESSION_AUTOSTART_CONFIG_GET_PRIVATE (self);
}


static void lxsession_lxsession_autostart_config_finalize (GObject* obj) {
	LxsessionLxsessionAutostartConfig * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_LXSESSION_AUTOSTART_CONFIG, LxsessionLxsessionAutostartConfig);
	_g_array_free0 (self->priv->stock_list);
	G_OBJECT_CLASS (lxsession_lxsession_autostart_config_parent_class)->finalize (obj);
}


GType lxsession_lxsession_autostart_config_get_type (void) {
	static volatile gsize lxsession_lxsession_autostart_config_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_lxsession_autostart_config_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionLxsessionAutostartConfigClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_lxsession_autostart_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionLxsessionAutostartConfig), 0, (GInstanceInitFunc) lxsession_lxsession_autostart_config_instance_init, NULL };
		GType lxsession_lxsession_autostart_config_type_id;
		lxsession_lxsession_autostart_config_type_id = g_type_register_static (G_TYPE_OBJECT, "LxsessionLxsessionAutostartConfig", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_lxsession_autostart_config_type_id__volatile, lxsession_lxsession_autostart_config_type_id);
	}
	return lxsession_lxsession_autostart_config_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



