#!/bin/bash -x
# File: "/etc/pm/sleep.d/99backlight".

TMP_FILE="/tmp/last_brightness"
BACKLIGHT_DIR="/sys/class/backlight/intel_backlight"
case "${1}" in
        hibernate)
		cat $BACKLIGHT_DIR/actual_brightness > $TMP_FILE
                ;;
	resume|thaw)
		LAST=$(cat $TMP_FILE | tr '\n' ' ' | sed -e 's/ $//')
		echo $LAST > $BACKLIGHT_DIR/brightness
		rm -f $TMP_FILE
		;;
esac
exit 0
