/* main-gtk.c generated by valac 0.22.1, the Vala compiler
 * generated from main-gtk.vala, do not modify */

/* 
 *      Copyright 2013 Julien Lavergne <gilir@ubuntu.com>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define LXSESSION_TYPE_GENERIC_WINDOW (lxsession_generic_window_get_type ())
#define LXSESSION_GENERIC_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_GENERIC_WINDOW, LxsessionGenericWindow))
#define LXSESSION_GENERIC_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_GENERIC_WINDOW, LxsessionGenericWindowClass))
#define LXSESSION_IS_GENERIC_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_GENERIC_WINDOW))
#define LXSESSION_IS_GENERIC_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_GENERIC_WINDOW))
#define LXSESSION_GENERIC_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_GENERIC_WINDOW, LxsessionGenericWindowClass))

typedef struct _LxsessionGenericWindow LxsessionGenericWindow;
typedef struct _LxsessionGenericWindowClass LxsessionGenericWindowClass;
typedef struct _LxsessionGenericWindowPrivate LxsessionGenericWindowPrivate;
typedef struct _Block1Data Block1Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define LXSESSION_TYPE_MAIN (lxsession_main_get_type ())
#define LXSESSION_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LXSESSION_TYPE_MAIN, LxsessionMain))
#define LXSESSION_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LXSESSION_TYPE_MAIN, LxsessionMainClass))
#define LXSESSION_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LXSESSION_TYPE_MAIN))
#define LXSESSION_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LXSESSION_TYPE_MAIN))
#define LXSESSION_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LXSESSION_TYPE_MAIN, LxsessionMainClass))

typedef struct _LxsessionMain LxsessionMain;
typedef struct _LxsessionMainClass LxsessionMainClass;
typedef struct _LxsessionMainPrivate LxsessionMainPrivate;
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _LxsessionGenericWindow {
	GtkWindow parent_instance;
	LxsessionGenericWindowPrivate * priv;
};

struct _LxsessionGenericWindowClass {
	GtkWindowClass parent_class;
};

struct _Block1Data {
	int _ref_count_;
	LxsessionGenericWindow * self;
	GtkMessageDialog* msg;
};

struct _LxsessionMain {
	GObject parent_instance;
	LxsessionMainPrivate * priv;
};

struct _LxsessionMainClass {
	GObjectClass parent_class;
};


static gpointer lxsession_generic_window_parent_class = NULL;
static gpointer lxsession_main_parent_class = NULL;
static gchar* lxsession_main_message;
static gchar* lxsession_main_message = NULL;
static gchar* lxsession_main_type;
static gchar* lxsession_main_type = NULL;

GType lxsession_generic_window_get_type (void) G_GNUC_CONST;
enum  {
	LXSESSION_GENERIC_WINDOW_DUMMY_PROPERTY
};
LxsessionGenericWindow* lxsession_generic_window_new (const gchar* message);
LxsessionGenericWindow* lxsession_generic_window_construct (GType object_type, const gchar* message);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void __lambda2_ (Block1Data* _data1_, gint response_id);
static void ___lambda2__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
GType lxsession_main_get_type (void) G_GNUC_CONST;
enum  {
	LXSESSION_MAIN_DUMMY_PROPERTY
};
gint lxsession_main_main (gchar** args, int args_length1);
LxsessionMain* lxsession_main_new (void);
LxsessionMain* lxsession_main_construct (GType object_type);
static void lxsession_main_finalize (GObject* obj);

static const GOptionEntry LXSESSION_MAIN_option_entries[3] = {{"message", 'm', 0, G_OPTION_ARG_STRING, &lxsession_main_message, "specify a string to be to displayed as a message", "NAME"}, {"type", 't', 0, G_OPTION_ARG_STRING, &lxsession_main_type, "specify the type of the message (w = warning, i = info)", "NAME"}, {NULL}};

static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		LxsessionGenericWindow * self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->msg);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


static void __lambda2_ (Block1Data* _data1_, gint response_id) {
	LxsessionGenericWindow * self;
	gint _tmp0_ = 0;
	self = _data1_->self;
	_tmp0_ = response_id;
	switch (_tmp0_) {
		case GTK_RESPONSE_OK:
		{
			FILE* _tmp1_ = NULL;
			_tmp1_ = stdout;
			fputs ("Ok\n", _tmp1_);
			break;
		}
		case GTK_RESPONSE_CANCEL:
		{
			FILE* _tmp2_ = NULL;
			_tmp2_ = stdout;
			fputs ("Cancel\n", _tmp2_);
			break;
		}
		case GTK_RESPONSE_DELETE_EVENT:
		{
			FILE* _tmp3_ = NULL;
			_tmp3_ = stdout;
			fputs ("Delete\n", _tmp3_);
			break;
		}
		default:
		break;
	}
	gtk_widget_destroy ((GtkWidget*) _data1_->msg);
	gtk_main_quit ();
}


static void ___lambda2__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	__lambda2_ (self, response_id);
}


LxsessionGenericWindow* lxsession_generic_window_construct (GType object_type, const gchar* message) {
	LxsessionGenericWindow * self = NULL;
	Block1Data* _data1_;
	const gchar* _tmp0_ = NULL;
	GtkMessageDialog* _tmp1_ = NULL;
	g_return_val_if_fail (message != NULL, NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	self = (LxsessionGenericWindow*) g_object_new (object_type, NULL);
	_data1_->self = g_object_ref (self);
	gtk_window_set_title ((GtkWindow*) self, "Lxsession Message");
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_window_set_default_size ((GtkWindow*) self, 350, 70);
	_tmp0_ = message;
	_tmp1_ = (GtkMessageDialog*) gtk_message_dialog_new ((GtkWindow*) self, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_OK_CANCEL, _tmp0_);
	g_object_ref_sink (_tmp1_);
	_data1_->msg = _tmp1_;
	g_signal_connect_data ((GtkDialog*) _data1_->msg, "response", (GCallback) ___lambda2__gtk_dialog_response, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	gtk_widget_show ((GtkWidget*) _data1_->msg);
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return self;
}


LxsessionGenericWindow* lxsession_generic_window_new (const gchar* message) {
	return lxsession_generic_window_construct (LXSESSION_TYPE_GENERIC_WINDOW, message);
}


static void lxsession_generic_window_class_init (LxsessionGenericWindowClass * klass) {
	lxsession_generic_window_parent_class = g_type_class_peek_parent (klass);
}


static void lxsession_generic_window_instance_init (LxsessionGenericWindow * self) {
}


GType lxsession_generic_window_get_type (void) {
	static volatile gsize lxsession_generic_window_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_generic_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionGenericWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_generic_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionGenericWindow), 0, (GInstanceInitFunc) lxsession_generic_window_instance_init, NULL };
		GType lxsession_generic_window_type_id;
		lxsession_generic_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "LxsessionGenericWindow", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_generic_window_type_id__volatile, lxsession_generic_window_type_id);
	}
	return lxsession_generic_window_type_id__volatile;
}


gint lxsession_main_main (gchar** args, int args_length1) {
	gint result = 0;
	LxsessionGenericWindow* app = NULL;
	const gchar* _tmp6_ = NULL;
	LxsessionGenericWindow* _tmp7_ = NULL;
	LxsessionGenericWindow* _tmp8_ = NULL;
	GError * _inner_error_ = NULL;
	{
		GOptionContext* options_args = NULL;
		GOptionContext* _tmp0_ = NULL;
		GOptionContext* _tmp1_ = NULL;
		GOptionContext* _tmp2_ = NULL;
		GOptionContext* _tmp3_ = NULL;
		_tmp0_ = g_option_context_new ("- Lxsession message utility");
		options_args = _tmp0_;
		_tmp1_ = options_args;
		g_option_context_set_help_enabled (_tmp1_, TRUE);
		_tmp2_ = options_args;
		g_option_context_add_main_entries (_tmp2_, LXSESSION_MAIN_option_entries, NULL);
		_tmp3_ = options_args;
		g_option_context_parse (_tmp3_, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (options_args);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch0_g_option_error;
			}
			_g_option_context_free0 (options_args);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_g_option_context_free0 (options_args);
	}
	goto __finally0;
	__catch0_g_option_error:
	{
		GError* e = NULL;
		GError* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = e;
		_tmp5_ = _tmp4_->message;
		g_critical ("main-gtk.vala:83: Option parsing failed: %s\n", _tmp5_);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	gtk_init (&args_length1, &args);
	_tmp6_ = lxsession_main_message;
	_tmp7_ = lxsession_generic_window_new (_tmp6_);
	g_object_ref_sink (_tmp7_);
	app = _tmp7_;
	_tmp8_ = app;
	gtk_widget_show_all ((GtkWidget*) _tmp8_);
	gtk_main ();
	result = 0;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return lxsession_main_main (argv, argc);
}


LxsessionMain* lxsession_main_construct (GType object_type) {
	LxsessionMain * self = NULL;
	self = (LxsessionMain*) g_object_new (object_type, NULL);
	return self;
}


LxsessionMain* lxsession_main_new (void) {
	return lxsession_main_construct (LXSESSION_TYPE_MAIN);
}


static void lxsession_main_class_init (LxsessionMainClass * klass) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	lxsession_main_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = lxsession_main_finalize;
	_tmp0_ = g_strdup ("");
	lxsession_main_message = _tmp0_;
	_tmp1_ = g_strdup ("");
	lxsession_main_type = _tmp1_;
}


static void lxsession_main_instance_init (LxsessionMain * self) {
}


static void lxsession_main_finalize (GObject* obj) {
	LxsessionMain * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LXSESSION_TYPE_MAIN, LxsessionMain);
	G_OBJECT_CLASS (lxsession_main_parent_class)->finalize (obj);
}


GType lxsession_main_get_type (void) {
	static volatile gsize lxsession_main_type_id__volatile = 0;
	if (g_once_init_enter (&lxsession_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LxsessionMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lxsession_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LxsessionMain), 0, (GInstanceInitFunc) lxsession_main_instance_init, NULL };
		GType lxsession_main_type_id;
		lxsession_main_type_id = g_type_register_static (G_TYPE_OBJECT, "LxsessionMain", &g_define_type_info, 0);
		g_once_init_leave (&lxsession_main_type_id__volatile, lxsession_main_type_id);
	}
	return lxsession_main_type_id__volatile;
}



